@extends('errors.layout')
@section('code', '404')
@section('icon', 'fas fa-search')
@section('title', 'الصفحة غير موجودة')
@section('description', 'عذراً، الصفحة التي تبحث عنها غير موجودة أو ربما تم نقلها أو حذفها.')
